Carts/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Carts.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {
            return View();
        }

		public ActionResult GetCart()
		{
			return PartialView("_CartPartial");
		}

		public ActionResult AddToCart(int id)
		{
			var currentCart = Models.Cart.Operation.GetCurrentCart();
			currentCart.AddProduct(id);
			return PartialView("_CartPartial");
		}

		public ActionResult RemoveFromCart(int id)
		{
			var currentCart = Models.Cart.Operation.GetCurrentCart();
			currentCart.RemoveProduct(id);
			return PartialView("_CartPartial");
		}

		public ActionResult ClearCart()
		{
			var currentCart = Models.Cart.Operation.GetCurrentCart();
			currentCart.ClearCart();
			return PartialView("_CartPartial");
		}
	}
}

Carts/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace Carts.Controllers
{
	public class OrderController : Controller
	{
		// GET: Order
		public ActionResult Index()
		{
			var userId = HttpContext.User.Identity.GetUserId();

			if (userId != null)
			{
				ViewBag.LinkableId = 666;
				return View();
			}
			else
			{
				return RedirectToAction("Login", "Account");
			}
		}
	}
}

Carts/Views/Shared/_CartPartial.cshtml
@{
	var currentCart = Carts.Models.Cart.Operation.GetCurrentCart();
}
<a id="CartDropDown" class="dropdown-toggle" data-toggle="dropdown">
	@String.Format(@Carts.Resource.Resource.Total + "${0} ({1})", currentCart.TotalAmount, currentCart.Count)
	<span class="caret"></span>
</a>
<ul class="dropdown-menu" role="menu" aria-labelledby="CartDropDown">
	@if (currentCart.Count > 0)
	{
		foreach (var cartitem in currentCart)
		{
			<li class="col-xs-12">
				<span class="col-xs-9">@cartitem.Name @cartitem.Price.ToString("0") X @cartitem.Quantity </span>
				<span class="btn btn-danger col-xs-2" onclick="RemoveFromCart('@cartitem.Id')">
					X
				</span>
			</li>
		}
		<li class="divider"></li>
		<li>
			<div id="CartButtons" class="col-xs-12">
				<a class="btn btn-success text-center col-xs-5" href="@Url.Action("Index","Order",new { })">
					@Carts.Resource.Resource.Checkout
				</a>
				<a class="btn btn-danger text-center  col-xs-5 col-xs-offset-2" onclick="ClearCart()">
					@Carts.Resource.Resource.Clean
				</a>
			</div>
		</li>
	}
	else
	{
		<li><a class="btn btn-default text-center" href="#">@Carts.Resource.Resource.No_item</a></li>
	}
</ul>

Carts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - My ASP.NET Application</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")

	<script type="text/javascript">
        function AddToCart(productId) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("AddToCart", "Cart")',
                data: { id: productId }
            })
            .done(function (msg) {
                $('li#Cart').html(msg);
            });
        }
        function RemoveFromCart(productId) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("RemoveFromCart", "Cart")',
                data: { id: productId }
            })
            .done(function (msg) {
                $('li#Cart').html(msg);
            });
		}

        function ClearCart() {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("ClearCart", "Cart")',
                data: {}
            })
            .done(function (msg) {
                $('li#Cart').html(msg);
            });
        }
	</script>
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				@Html.ActionLink(@Carts.Resource.Resource.ShopTitle, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink(@Carts.Resource.Resource.Home, "Index", "Home")</li>
					<li>@Html.ActionLink(@Carts.Resource.Resource.Product, "Index", "Product")</li>
					<li class="dropdown">
						<a data-toggle="dropdown" href="#">@Carts.Resource.Resource.Language</a>
						<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
							<li>@Html.ActionLink("English", "SetCulture", "Home", new { culture = "en-US", returnUrl = this.Request.RawUrl }, null)</li>
							<li>@Html.ActionLink("中文", "SetCulture", "Home", new { culture = "zh-TW", returnUrl = this.Request.RawUrl }, null)</li>
						</ul>
					</li>
					<li id="Cart">
						@Html.Partial("_CartPartial")
					</li>
				</ul>
				@Html.Partial("_LoginPartial")
			</div>
		</div>
	</div>
	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
		</footer>
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
</body>
</html>